- name: install nginx
  hosts: local
  become: yes
  tasks:
  - name: Install nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
