- name: username and password
  hosts: frontend
  vars:
  - name: username
    prompt: enter username
    private: true

  - name: password
    prompt: enter password
    private: true

  tasks:
    - name: print username and password
      ansible.builtin.debug:
        msg: "hello username: {{username}}, and password {{password}}"
