- name: Install nginx
  hosts: front
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.debug:
        name: nginx
        state: present
    - name: start nginx
      ansible.builtin.debug:
        name: start nginx
        state: started
        enabled: yes   