- name: installing packages
  hosts: frontend
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.package:
        name: "{{items}}"
        state: present

      loop:
      - mysql
      - nginx
      - zip
