- name: PLAY1
  hosts: local
  connection: local
  tasks:
  - name: PLAY1 and task1
    ansible.builtin.debug:
      msg: "Hello from play 1 and task 1"
  
  - name: PLAY2 and task2
    ansible.builtin.debug:
      msg: "Hello from PLAY2 and task 2"

- name: PLAY2
  hosts: local
  connection: local
  tasks:
  - name: PLAY2 and task1
    ansible.builtin.debug:
      msg: "Hello from play 2 and task 1"
  
  - name: PLAY2 and task2
    ansible.builtin.debug:
      msg: "Hello from PLAY2 and task 2"