- name: install mysql
  hosts: frontend
  become: yes
  tasks:
    - name: installing database
      ansible.builtin.dnf:
        name: mysql
        state: present
    
    - name: start and enable service
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes