- name: app-setup
  include_role:
    name: common
    tasks_from: app-setup

- name: nodejs-setup
  include_role:
    name: common
    tasks_from: nodejs


- name: create system user
  ansible.builtin.user:
    name: roboshop
    shell: /sbin/nologin
    system: true
    home: /app

- name: download catalogue code
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
    dest: /tmp/catalogue.zip

- name: extract catalogue code
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app
    remote_src: yes

- name: install dependencies
  community.general.npm:
    path: /app



- name: copy mongodb repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present



- name: check products loaded or not
  ansible.builtin.command: mongosh --host mongodb.blackweb.agency --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output

- name: print catalogue output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"

- name: load products
  ansible.builtin.shell: mongosh --host mongodb.blackweb.agency < /app/db/master-data.js
  when: catalogue_output.stdout | int < 0

- name: app
  include_role:
    name: common
    tasks: systemd.yaml