- name: copy catalogue service
  ansible.builtin.template:
    src: catalogue.service.j2
    dest: /etc/systemd/system/catalogue.service

- name: sytemctl daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable service
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes