- name: Install nginx
  hosts: frontend
  become: yes
  tasks:
    - name: Installing nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
