- name: install packages
  hosts: frontend
  tasks:
    - name: installing required packages
      ansible.builtin.package:
        name: "{{item}}"
        state: present
      loop:
      - mysql
      - zip
      - nginx