- name: install packages
  hosts: frontend
  tasks:
    - name: installing reuired packages
      ansible.builtin.packages:
        name: "{{items}}"
        state: installed
      loop:
      - mysql
      - zip
      - nginx