- name: install packages
  hosts: frontend
  tasks:
    - name: install packages
      ansible.builtin.package:
        name: "{{item}}"
        state: "{{item.state}}"
      loop:
      - {name: 'nginx', state: 'present'}
      - {name: 'mysql', state: 'absent'}
      - {name: 'zip', state: 'absent'}
