- name: username
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: please enter your username
    private: true
  - name: password
    prompt: enter password
    private: true

  tasks:
  - name: username and password
    ansible.builtin.debug:
      msg: "hello username is {{ username }}, password is {{password}}"