- name: Create Roboshop User
  hosts: local
  connection: local
  tasks:
  - name: check roboshop user exits or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true

  - name: create roboshop user
    become: yes
    ansible.builtin.command: useradd roboshop
    when: output.rc !=0

  - name: user already exits
    ansible.builtin.debug:
      msg: "user already exists"
    when: output.rc ==0
